config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  resources :contacts
  get 'contact-us', to: 'contacts#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
   validates :name, presence: true
   validates :email, presence: true
   validates :comments, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
 def new
   @contact = Contact.new
 end
 
 def create
   @contact = Contact.new(contact_params)
   if @contact.save
     flash[:success] = "Message sent."
     redirect_to new_contact_path
   else
     flash[:danger] = @contact.errors.full_messages.join(", ")
     redirect_to new_contact_path
   end
 end
 
 private
  def contact_params
    params.require(:contact).permit(:name, :email, :comments)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center">Contact Us</h3>
    
    <div class="col-md-4 col-md-offset-4">
      <%= flash[:notice] %>
      <div class="well">
        <%= form_for @contact do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class: 'form-control' %>
          </div>
        
          <%= f.submit 'Submit', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Saasapp</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-static-top" role="navigation">
      <div class='container'>
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
          <%= link_to root_path, class:"navbar-brand" do %>
            <i class="fa fa-group"></i>
            DevMatch
          <% end %>
        </div>
        <div class="collapse navbar-collapse" id="main-nav-collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About", about_path %></li>
            <li><%= link_to "Contact Us", new_contact_path %></li>
          </ul>
        </div><!.navbar-collapse -->
      </div>
    </nav>
    
      <div class="container">
        <% flash.each do |type, msg| %>
          <%= content_tag :div, msg, class: "alert alert-#{type}" %>
        <% end %>
      </div>
   <%= yield %>

  </body>
</html>

app/views/pages/about.html.erb
<div class= "container text-center">
  <h1>About Page</h1>
  <p>We are DevMatch.  Our company focuses on creating an exclusive community
  for developers and entrepreneurs to meet.</p>
</div>

app/views/pages/home.html.erb
<div class="home-callout text-center container-fluid">
  <h1>Welcome to DevMatch</h1>
  <h3>A membership site where entrepreneurs can meet developers.</h3>
</div>